const response = {
    status: true,
    message: 'retrieved successfully',
    data: [
        {
            id: 32835,
            course_id: 1,
            topic_id: 0,
            qid: '02MSS199710057',
            text: 'When income rises, less of a good is bought. This situation describes&nbsp;',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-10-06T13:12:16.000000Z',
            updated_at: '2011-10-06T13:12:16.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 128291,
                    question_id: 32835,
                    text: 'a giffen good',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-06T13:12:16.000000Z',
                    updated_at: '2011-10-06T13:12:16.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 128292,
                    question_id: 32835,
                    text: 'a superior good',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-06T13:12:16.000000Z',
                    updated_at: '2011-10-06T13:12:16.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 128293,
                    question_id: 32835,
                    text: 'an inferior good',
                    value: 1,
                    solution: '',
                    created_at: '2011-10-06T13:12:16.000000Z',
                    updated_at: '2011-10-06T13:12:16.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 128294,
                    question_id: 32835,
                    text: 'an ostentatious good',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-06T13:12:16.000000Z',
                    updated_at: '2011-10-06T13:12:16.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 373,
            course_id: 1,
            topic_id: 27,
            qid: 'Q1380',
            text: '<p>All the following are objectives of industrialisation in Ghana except to</p>',
            instructions: '',
            resource: '',
            options: '',
            position: 1,
            created_at: '2018-06-06T15:29:13.000000Z',
            updated_at: '2018-06-06T15:29:13.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2","10617"]',
            editor_id: null,
            topic: {
                id: 27,
                course_id: 1,
                topicID: '01SS10EC17',
                name: 'INDUSTRIALISATION',
                author: 'content@ecoachsolutions.com',
                description: '',
                notes: '',
                category: '',
                created_at: '2011-08-02T11:40:21.000000Z',
                updated_at: '2011-08-02T11:40:21.000000Z',
                confirmed: 1,
                public: 1,
                N: 37,
                p: 37,
                editors: '["3","2"]',
                editor_id: null,
            },
            answers: [
                {
                    id: 1531,
                    question_id: 373,
                    text: '<p>Diversify the economy</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-07-29T00:00:00.000000Z',
                    updated_at: '2011-07-29T00:00:00.000000Z',
                    answer_order: null,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1532,
                    question_id: 373,
                    text: '<p>Create employment</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-07-29T00:00:00.000000Z',
                    updated_at: '2011-07-29T00:00:00.000000Z',
                    answer_order: null,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1533,
                    question_id: 373,
                    text: '<p>Reduce importation</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-07-29T00:00:00.000000Z',
                    updated_at: '2011-07-29T00:00:00.000000Z',
                    answer_order: null,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1534,
                    question_id: 373,
                    text: '<p>Maximise profit</p>',
                    value: 1,
                    solution:
                        '<p>The government does not establish industries with the aim of maximising profit butto promote development.</p>',
                    created_at: '2011-07-29T00:00:00.000000Z',
                    updated_at: '2011-07-29T00:00:00.000000Z',
                    answer_order: null,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 19568,
            course_id: 1,
            topic_id: 0,
            qid: '015510EC00867',
            text: 'Which of the following is equivalent to the national income?',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-08-23T09:24:12.000000Z',
            updated_at: '2011-08-23T09:27:20.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 77249,
                    question_id: 19568,
                    text: 'Gross national product at factor cost',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-23T09:24:12.000000Z',
                    updated_at: '2011-08-23T09:27:20.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 77250,
                    question_id: 19568,
                    text: 'Net National product at factor cost',
                    value: 1,
                    solution: '',
                    created_at: '2011-08-23T09:24:12.000000Z',
                    updated_at: '2011-08-23T09:27:20.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 77251,
                    question_id: 19568,
                    text: 'Net national product at market prices',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-23T09:24:12.000000Z',
                    updated_at: '2011-08-23T09:27:20.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 77252,
                    question_id: 19568,
                    text: 'Gross National product at market',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-23T09:24:12.000000Z',
                    updated_at: '2011-08-23T09:27:21.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 132722,
            course_id: 1,
            topic_id: 0,
            qid: '0000000000000',
            text: '<p><br></p>',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2016-03-14T15:46:59.000000Z',
            updated_at: '2019-03-05T17:40:53.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["4668","10617"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 717506,
                    question_id: 132722,
                    text: '<p>Question 5</p><p>Explain five ways by which self-reliance can be achieved in Ghana.</p>',
                    value: 0,
                    solution:
                        "<p>Question 5</p><p>Explain five ways by which self-reliance can be achieved in Ghana.</p><p>The following are some of the measures that Ghana can use to be self-reliant </p><p>i. Adoption of strategic medium/long term plan to minimize dependence on other countries: Ghana can be self-reliant if she can diversify her agricultural sector so that she can reduce her dependence on foreign goods like electronics, alcoholic beverages, textile prints, sandals, shoes, tooth pick, cooking utensils, etc. which can be produced locally. Ghana relies mostly on the export of cocoa beans as the major export crop and a major foreign exchange earner. When the revenue from our cocoa falls as a result of the fall in the price in the world market, it affects the country's ability to finance her development projects since the foreign exchange from our cocoa export will not be enough to import machines, tractors, combine harvesters, equipment, tools, etc. the country needs. The government can set up agro-processing industries to process agricultural products like cocoa beans, into cocoa paste, cake, chocolate and cocoa butter for local use and for export. Ghana government can be self-reliant by reducing her dependence on foreign financial assistance since some foreign loans may be given to build places of convenience which may not be what the people need but rather the people want schools or clinics.</p><p>ii. Development of positive work attitudes/ethics: Citizens can demonstrate their dedication to duty and hard work to increase productivity. Workers must be given re-orientation on attitudes towards work by organising workshops and seminars for workers and managerial staff on time management and good work ethics. A worker should be punctual, regular, highly committed to his work. He should have respect for time and report early to work. He should not leave his work unattended to and walk aimlessly about. A worker with a high sense of duty shows concern, care and compassion in dealing with the business public. Goods and services are delivered on time to customers and with maximum amount of care.</p><p>iii. Development of human resources through education and training: Human resource of Ghana can be improved through training. Through training, one acquires the practical skills for a job. The trainee is taught practically the rudiments of the trade or profession. Thus through training, one acquires knowledge, skills and attitude for a specific purpose or job. An individual needs to be trained by specialists in his chosen field to help him contribute effectively to national development. Someone who is interested in nursing can never become a professional nurse if he does not undergo training in a nursing school. Our natural resources can be developed through research on utilization, provision of equipment for exploration and processing. </p><p>iv. Encouraging the consumption of made-in-Ghana goods: Foreign cultural influences have affected the demand for locally made goods like food, leather works and clothes. There is therefore the need to reverse this trend. The youth must patronize locally produced goods as this will go a long way to increase demand for these goods and also help to improve the quality of the goods through suggestions and comments they make to producers. As more youth patronize locally made goods there will be an increase in demand for the goods and this will encourage producers to employ more youth to produce these goods for local use and for export to earn more foreign exchange for the country's socio-economic development.</p><p>V. Adopting modern technology and promoting research work: The adoption of modern technology such as mechanized farming where farmers use irrigation, combine harvesters, planters, ploughs, herbicides and fertilizers in farming help to increase agricultural yield for home supply and export to earn foreign exchange. The agricultural products such as cocoa, cotton, rubber, etc. can also serve as raw materials for the local industries. The promotion of research work in farming can help to improve productivity. The establishment of agricultural research centres like Council for Scientific Research (CSIR) makes its research findings available for the nation. The CSIR has come out with new varieties of crops (e.g. maize, cassava, yams, plantains and rice which have high yielding and disease / pest resistant / tolerant, with high nutritional quality and requiring low inputs of fertilizers and herbicides. The release of these improved varieties and their application technologies have contributed significantly to food security and the national economy.</p><p>vi. Ensuring democracy and good governance: Ghana can be self-reliant by ensuring democracy and good governance. This means that leaders and followers must adhere to the rule of law to ensure peace and stability. When rule of law prevails, no citizen can be unlawfully arrested and imprisoned without a fair trial by an accepted law court. There should be equality before the laws of the land without any discrimination or favouritism because of one's background or affiliation. So all citizens must have equal opportunity to hold public office and contribute towards the development of the nation.</p><p>vii. Adoption of change in mentality: In order for Ghana to achieve self-reliance Ghanaians need to have a change in mentality. The mentalityof Ghanaians is that, most Ghanaian goods are fake or sub-standard whereas the foreign imported goods are of good quality. We need to patronize the locally made goods like sandals, shoes toilet soap, edible oil, textile etc. to encourage local manufacturers to increase their production and create more employment for our local people. This will benefit the entire country since taxes will be collected from the local manufacturers to increase government revenue needed for development projects like schools, hospitals, etc. Ghanaians also need to change their mentality that Government work is nobody's work and therefore one should not put in much effort in doing one's assigned duty. This mentality reduces output and affects the economy of the country. Ghanaians must know that if they change their mentality in their workplace, this will lead to increase in output and enable the government to export more and be able to increase salaries.</p><p>viii. Promotion of industrialization: Ghana can achieve self-reliance by increasing the number of processing industries in the country. Ghana produces many primary products like cocoa, shea butter, cashew nut, citrus fruits and minerals like gold, diamond, etc. The country has not enough processing companies to process these products into finished goods for export. Though Ghana has chocolate factory at Tema, we import chocolate and many cocoa products from other countries. The government can achieve self-reliance by creating an enabling environment which will encourage private firms or individuals to come together to establish processing factories to process cocoa locally into pomade, hair and body creams for local use and for export. These exports will reduce our dependence on similar goods which are imported and also reduce the foreign exchange spent on their import.</p><p>ix. Efficient tax system: Taxes are common ways of restricting the important of selected goods such as luxuries and goods like cigarettes, alcoholic drinks, foreign textiles, etc. into the country in order to conserve foreign exchange for other uses and as corrective measures for the country's adverse balance payments position. Taxes on imports and exports are a way of raising revenue for the nation. The government must expand the tax base to cover all categories of traders so that the national revenue will increase.</p><p>x. Re-orientation of the educational system: Ghana can be self-reliant if the government can change the education system. The current education system which is too bookish does not help students to acquire skills needed by industries or which does help them to set up their own businesses. The government should set up more vocational and technical institutions, polytechnics and colleges of technology which can equip the students with skills and expertise, which the country needs to process her natural resources and undertake the manufacture of machines and tools for the local industries. When students acquire skills and expertise from such institutions they can set up their own businesses of form co-operative to establish their own businesses. </p>",
                    created_at: '2016-03-14T15:46:59.000000Z',
                    updated_at: '2016-03-14T15:46:59.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 245,
            course_id: 1,
            topic_id: 5,
            qid: '01SS10EC28029',
            text: '<p>Which one of the following can limit the practice of division of labour?</p>',
            instructions: '',
            resource: '',
            options: '',
            position: 30,
            created_at: '2018-06-08T01:06:49.000000Z',
            updated_at: '2018-06-08T01:06:49.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2",null]',
            editor_id: null,
            topic: {
                id: 5,
                course_id: 1,
                topicID: '01SS10EC28',
                name: 'LABOUR FORCE',
                author: 'content@ecoachsolutions.com',
                description: '',
                notes: '',
                category: '',
                created_at: '2011-08-02T11:51:13.000000Z',
                updated_at: '2011-08-02T11:51:13.000000Z',
                confirmed: 1,
                public: 1,
                N: 68,
                p: 45,
                editors: '["3","2"]',
                editor_id: null,
            },
            answers: [
                {
                    id: 1000,
                    question_id: 245,
                    text: '<p>A large market</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-04T01:07:37.000000Z',
                    updated_at: '2011-08-04T01:07:37.000000Z',
                    answer_order: 4,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1001,
                    question_id: 245,
                    text: '<p>Increased capital to employ more workers</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-04T01:07:37.000000Z',
                    updated_at: '2011-08-04T01:07:37.000000Z',
                    answer_order: 3,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1002,
                    question_id: 245,
                    text: '<p>The availability of many skilled workers</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-04T01:07:37.000000Z',
                    updated_at: '2011-08-04T01:07:37.000000Z',
                    answer_order: 1,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1003,
                    question_id: 245,
                    text: '<p>Level of technological development</p>',
                    value: 1,
                    solution:
                        '<p>If the firm adopts high technology so that it expands output and there is no market for the goods, it can limit the practice of division of labour.</p><p><strong>However, </strong><strong><em data-redactor-tag="em">Ans A </em></strong><em>(large market) </em>rather encourages division of labour since the large production will beabsorbed through large market. Similarly, the <em>availablity </em><em>of many skilled labour</em> <em><strong data-redactor-tag="strong">(ie. Ans C) </strong></em>enhances efficiency of labour resulting in internal economies of scale (large scale production)</p>',
                    created_at: '2011-08-04T01:07:37.000000Z',
                    updated_at: '2011-08-04T01:07:37.000000Z',
                    answer_order: 2,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 16677,
            course_id: 1,
            topic_id: 0,
            qid: '015510EC00144',
            text: 'The pursuit of profits and private ownership of property are common features of&nbsp;',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-08-12T09:24:41.000000Z',
            updated_at: '2011-08-12T09:24:41.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 65384,
                    question_id: 16677,
                    text: 'Socialism',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T09:24:41.000000Z',
                    updated_at: '2011-08-12T09:24:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 65385,
                    question_id: 16677,
                    text: 'Individualism',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T09:24:41.000000Z',
                    updated_at: '2011-08-12T09:24:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 65386,
                    question_id: 16677,
                    text: 'Communism',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T09:24:41.000000Z',
                    updated_at: '2011-08-12T09:24:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 65387,
                    question_id: 16677,
                    text: 'Capitalism',
                    value: 1,
                    solution: '',
                    created_at: '2011-08-12T09:24:41.000000Z',
                    updated_at: '2011-08-12T09:24:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 33426,
            course_id: 1,
            topic_id: 0,
            qid: '02MSS202010024',
            text: 'When do fixed inputs become variable?',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-10-07T19:16:43.000000Z',
            updated_at: '2011-10-07T19:16:43.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 130655,
                    question_id: 33426,
                    text: 'in the short run',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-07T19:16:43.000000Z',
                    updated_at: '2011-10-07T20:26:58.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 130656,
                    question_id: 33426,
                    text: 'in the long run',
                    value: 1,
                    solution: '',
                    created_at: '2011-10-07T19:16:43.000000Z',
                    updated_at: '2011-10-07T20:26:58.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 130657,
                    question_id: 33426,
                    text: 'when total product increases',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-07T19:16:43.000000Z',
                    updated_at: '2011-10-07T19:16:43.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 130658,
                    question_id: 33426,
                    text: 'when total product dimishes',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-07T19:16:43.000000Z',
                    updated_at: '2011-10-07T19:16:43.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 134463,
            course_id: 1,
            topic_id: 0,
            qid: '0000000000000',
            text: '<p><br></p>',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2016-05-18T10:34:20.000000Z',
            updated_at: '2019-03-18T23:48:41.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["4668",null,"10617"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 729691,
                    question_id: 134463,
                    text: '<p> Differentiate between money cost and social cost.</p>',
                    value: 0,
                    solution:
                        '<p>Money cost refers to the amount ofmoney spent to procure, buy or get an item. E.g. if \u00c2\u00a2 l 0.00 is spent on the purchase of a bag of cement, the money cost is the \u00c2\u00a2 10.00 spent. On the other hand, social cost refers to the inconveniences and consequences that the society suffers as a result of an activity carried on by another party or group of people. An examples is the effect of air pollution, water pollution, indiscriminate felling oftrees on the health ofthe people etc.</p>',
                    created_at: '2016-05-18T10:34:20.000000Z',
                    updated_at: '2016-05-18T10:34:20.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 729690,
                    question_id: 134463,
                    text: '<p>Of what importance is opportunity cost to the</p><p>(i) individual ( ii) \u00ef\u00ac\u0081rm (iii) government</p>',
                    value: 0,
                    solution:
                        '<p>(i) Opportunity cost is ofgreat importance to the individual. It enables the individual to makejudicious use ofhis scarce resource. Individual wants, desires or needs are unlimited but resources to satisfy all the needs of the individual are scarce or inadequate. Therefore, the scarce resources are usedto buy and consume items from which high satisfaction can be derived</p><p>ii) <b>It helps the \u00ef\u00ac\u0081rm to decide on which resources to use in production of its chosen product.</b></p><p>For instance, the \u00ef\u00ac\u0081rm will consider the cost-effective method of production and use the scarce resources to produce goods for which there is high pro\u00ef\u00ac\u0081t due to low cost of production and high demand.</p><p>(iii) It also helps thegovernment in the preparation ofbudget and aids government in policy making. Since government is confronted with numerous developmental projects but the resources needed to satisfy them are woefully inadequate, in formulating economic policies, government will consider its priority areas before the execution ofother projects. For example, if the government is faced with the choice ofconstructing roads and presidential palace, based on its scarce resources, the government may decide to construct the road \u00ef\u00ac\u0081rst before the construction ofthe presidential palace.</p><p>The reason is that, the road network will help easy transportation of goods and humans, hence accelerating economic growth and development.</p>',
                    created_at: '2016-05-18T10:34:20.000000Z',
                    updated_at: '2016-05-18T10:34:20.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 729689,
                    question_id: 134463,
                    text: '<p>Explain Opportunity Cost.</p>',
                    value: 0,
                    solution:
                        '<p>\n\t1.\n</p>\n<p>\n\tOpportunity Cost in economics is the alternative sacri\u00ef\u00ac\u0081ce made in order to enjoy something else. It is also de\u00ef\u00ac\u0081ned as the alternative forgone of an item in order to enjoy another one.\n</p>\n<p>\n\tFor instance, if jojo has an amount of\u00c2\u00a2 l 0, he can use this money to buy either a school bag or a pair of sandals all costing \u00c2\u00a2 l0 each. If jojo decides to buy the school bag, the opportunity cost of buying the school bag is the alternative sacri\u00ef\u00ac\u0081ced or forgone (i.e. the pair of sandals). The concept of opportunity cost or real cost arises due to scarcity of resources to satisfy all human needs desires. goals etc.\n</p>',
                    created_at: '2016-05-18T10:34:20.000000Z',
                    updated_at: '2016-05-18T10:34:20.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 33814,
            course_id: 1,
            topic_id: 0,
            qid: '02MSS200910001',
            text: 'Economics primarily deals with the',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-10-14T08:00:01.000000Z',
            updated_at: '2011-10-14T08:00:01.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 132207,
                    question_id: 33814,
                    text: 'employment of factors of production',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-14T08:00:01.000000Z',
                    updated_at: '2011-10-14T08:00:01.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 132208,
                    question_id: 33814,
                    text: 'consumption of goods and services',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-14T08:00:01.000000Z',
                    updated_at: '2011-10-14T08:00:01.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 132209,
                    question_id: 33814,
                    text: 'exchange of goods and services',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-14T08:00:01.000000Z',
                    updated_at: '2011-10-14T08:00:01.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 132210,
                    question_id: 33814,
                    text: 'management of scarce resources',
                    value: 1,
                    solution: '',
                    created_at: '2011-10-14T08:00:01.000000Z',
                    updated_at: '2011-10-14T08:00:01.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 59007,
            course_id: 1,
            topic_id: 0,
            qid: '0000000000000',
            text: '<p>One measure government can adopt to control inflation is to</p>',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2014-07-14T12:11:13.000000Z',
            updated_at: '2014-07-14T12:14:08.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 254135,
                    question_id: 59007,
                    text: '<p>increase government expenditure</p>',
                    value: 1,
                    solution: '',
                    created_at: '2014-07-14T12:11:13.000000Z',
                    updated_at: '2014-07-14T12:11:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 254136,
                    question_id: 59007,
                    text: '<p>buy securities from the open market</p>',
                    value: 0,
                    solution: '',
                    created_at: '2014-07-14T12:11:13.000000Z',
                    updated_at: '2014-07-14T12:11:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 254137,
                    question_id: 59007,
                    text: '<p>decrease taxes on wages and salaries</p>',
                    value: 0,
                    solution: '',
                    created_at: '2014-07-14T12:11:13.000000Z',
                    updated_at: '2014-07-14T12:11:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 254138,
                    question_id: 59007,
                    text: '<p>grant more loans to consumers</p>',
                    value: 0,
                    solution: '',
                    created_at: '2014-07-14T12:11:13.000000Z',
                    updated_at: '2014-07-14T12:11:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 18335,
            course_id: 1,
            topic_id: 0,
            qid: '015510EC00507',
            text: 'An inferior good is a commodity whose demand',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-08-17T14:14:41.000000Z',
            updated_at: '2011-08-17T14:14:41.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 72521,
                    question_id: 18335,
                    text: 'Falls as income increases',
                    value: 1,
                    solution: '',
                    created_at: '2011-08-17T14:14:41.000000Z',
                    updated_at: '2011-08-17T14:14:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 72522,
                    question_id: 18335,
                    text: 'Remains constant as income increases',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-17T14:14:41.000000Z',
                    updated_at: '2011-08-17T14:14:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 72523,
                    question_id: 18335,
                    text: 'Rises as income increases',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-17T14:14:41.000000Z',
                    updated_at: '2011-08-17T14:14:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 72524,
                    question_id: 18335,
                    text: 'Remains constant as income falls',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-17T14:14:41.000000Z',
                    updated_at: '2011-08-17T14:14:41.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 61,
            course_id: 1,
            topic_id: 2,
            qid: '01SS10EC29055',
            text: '<p>John opted to watch soccer every sunday afternoon rather than read in the library. To John, reading is</p>',
            instructions: '',
            resource: '',
            options: '',
            position: 59,
            created_at: '2018-06-11T23:20:42.000000Z',
            updated_at: '2018-06-11T23:20:42.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2","10617"]',
            editor_id: null,
            topic: {
                id: 2,
                course_id: 1,
                topicID: '01SS10EC29',
                name: 'SCOPE OF ECONOMICS',
                author: 'content@ecoachsolutions.com',
                description: '',
                notes: '',
                category: '',
                created_at: '2011-08-03T00:00:00.000000Z',
                updated_at: '2013-11-06T02:57:41.000000Z',
                confirmed: 1,
                public: 1,
                N: 115,
                p: 55,
                editors: '["3","2"]',
                editor_id: null,
            },
            answers: [
                {
                    id: 248,
                    question_id: 61,
                    text: '<p>Economic cost</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-03T05:57:42.000000Z',
                    updated_at: '2011-08-03T05:57:42.000000Z',
                    answer_order: 1,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 249,
                    question_id: 61,
                    text: '<p>Real cost</p>',
                    value: 1,
                    solution:
                        '<p>john decided to watch soccer at the time he had to go the library to read.in a way to, he sacrificed the library for the watching of soccer (probably he is a strong soccer fun)</p>',
                    created_at: '2011-08-03T05:57:42.000000Z',
                    updated_at: '2011-08-03T05:57:42.000000Z',
                    answer_order: 2,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 250,
                    question_id: 61,
                    text: '<p>Implicit cost</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-03T05:57:42.000000Z',
                    updated_at: '2011-08-03T05:57:42.000000Z',
                    answer_order: 3,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 256,
                    question_id: 61,
                    text: '<p>explicit cost</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-03T05:57:42.000000Z',
                    updated_at: '2011-08-03T05:57:42.000000Z',
                    answer_order: 4,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 33275,
            course_id: 1,
            topic_id: 0,
            qid: '02MSS201210043',
            text: 'Which of the following is conceptually equivalent to the national income?',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-10-07T12:17:34.000000Z',
            updated_at: '2011-10-07T12:17:34.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 130051,
                    question_id: 33275,
                    text: 'net national prouct at market prices',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-07T12:17:34.000000Z',
                    updated_at: '2011-10-07T12:17:34.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 130052,
                    question_id: 33275,
                    text: 'net national product at factor cost',
                    value: 1,
                    solution: '',
                    created_at: '2011-10-07T12:17:34.000000Z',
                    updated_at: '2011-10-07T12:17:34.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 130053,
                    question_id: 33275,
                    text: 'net domestic product at market prices',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-07T12:17:34.000000Z',
                    updated_at: '2011-10-07T12:17:34.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 130054,
                    question_id: 33275,
                    text: 'net domestic product at factor cost',
                    value: 0,
                    solution: '',
                    created_at: '2011-10-07T12:17:34.000000Z',
                    updated_at: '2011-10-07T12:17:34.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 38353,
            course_id: 1,
            topic_id: 13,
            qid: '0000000000000',
            text: '<p>When commodities are in short supply, government should immediately intervene by\u00c2\u00a0</p>',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2013-11-06T12:41:48.000000Z',
            updated_at: '2018-06-11T15:00:34.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2","10617"]',
            editor_id: null,
            topic: {
                id: 13,
                course_id: 1,
                topicID: '01SS10EC07',
                name: 'PRICE CONTROL',
                author: 'content@ecoachsolutions.com',
                description: '',
                notes: '',
                category: '',
                created_at: '2011-08-02T11:32:14.000000Z',
                updated_at: '2011-08-02T11:32:14.000000Z',
                confirmed: 1,
                public: 1,
                N: 26,
                p: 26,
                editors: '["2"]',
                editor_id: null,
            },
            answers: [
                {
                    id: 150865,
                    question_id: 38353,
                    text: '<p>providing subsides to businesses\u00c2\u00a0</p>',
                    value: 0,
                    solution: '',
                    created_at: '2013-11-06T12:41:48.000000Z',
                    updated_at: '2013-11-06T12:41:48.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 150866,
                    question_id: 38353,
                    text: '<p>increasing the level of taxation</p>',
                    value: 0,
                    solution: '',
                    created_at: '2013-11-06T12:41:48.000000Z',
                    updated_at: '2013-11-06T12:41:48.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 150867,
                    question_id: 38353,
                    text: '<p>rationing goods and services\u00c2\u00a0</p>',
                    value: 1,
                    solution:
                        '<p>Rationing is a means the government uses to distribute scare goods by restricting consumers to specified quantities. Coupons and chits are offered to ensure that many people can get access to the scarce goods.</p>',
                    created_at: '2013-11-06T12:41:48.000000Z',
                    updated_at: '2013-11-06T12:41:48.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 150868,
                    question_id: 38353,
                    text: '<p>establishing more business organizations\u00c2\u00a0</p>',
                    value: 0,
                    solution: '',
                    created_at: '2013-11-06T12:41:48.000000Z',
                    updated_at: '2013-11-06T12:41:48.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 150869,
                    question_id: 38353,
                    text: '<p>*Answer Text*</p>',
                    value: 0,
                    solution: '',
                    created_at: '2013-11-06T12:41:48.000000Z',
                    updated_at: '2013-11-06T12:41:48.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 0,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 52,
            course_id: 1,
            topic_id: 2,
            qid: '01SS10EC29046',
            text: '<p>The consumer has to forgo alternative because</p>',
            instructions: '',
            resource: '',
            options: '',
            position: 50,
            created_at: '2018-06-11T23:15:01.000000Z',
            updated_at: '2018-06-11T23:15:01.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2","10617"]',
            editor_id: null,
            topic: {
                id: 2,
                course_id: 1,
                topicID: '01SS10EC29',
                name: 'SCOPE OF ECONOMICS',
                author: 'content@ecoachsolutions.com',
                description: '',
                notes: '',
                category: '',
                created_at: '2011-08-03T00:00:00.000000Z',
                updated_at: '2013-11-06T02:57:41.000000Z',
                confirmed: 1,
                public: 1,
                N: 115,
                p: 55,
                editors: '["3","2"]',
                editor_id: null,
            },
            answers: [
                {
                    id: 211,
                    question_id: 52,
                    text: '<p>satisffacton cannot be maximized</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-02T23:53:51.000000Z',
                    updated_at: '2011-08-02T23:53:51.000000Z',
                    answer_order: 1,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 212,
                    question_id: 52,
                    text: '<p>scale of preference cannot be ordered</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-02T23:53:51.000000Z',
                    updated_at: '2011-08-02T23:53:51.000000Z',
                    answer_order: 2,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 213,
                    question_id: 52,
                    text: '<p>material needs are limited</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-02T23:53:51.000000Z',
                    updated_at: '2011-08-02T23:53:51.000000Z',
                    answer_order: 3,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 214,
                    question_id: 52,
                    text: '<p>resources are scarce</p>',
                    value: 1,
                    solution:
                        '<p>since resources are scarce but the wants are unlimited, some wants have to be purchased or met while others have to be forgone or sacrificed. in other words, oppotunity cost will rise so long as the resources are scarce and for that matter all wants cannot be satisfied. those wants that cannot be satisfied constitute the real or opportunity cost</p>',
                    created_at: '2011-08-02T23:53:51.000000Z',
                    updated_at: '2011-08-02T23:53:51.000000Z',
                    answer_order: 4,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 16203,
            course_id: 1,
            topic_id: 0,
            qid: '015510EC00003',
            text: 'Which of the following in not a macro economic goal?',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-08-11T06:43:13.000000Z',
            updated_at: '2011-08-11T06:43:13.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 63355,
                    question_id: 16203,
                    text: 'Promotion of competition',
                    value: 1,
                    solution:
                        'Sicne microeconomics concerns with economic issues that affect the economy as a whole, its main goal is to identify the factors that influence the level of employment.(ie. Ans B). Stabilization of general price levels (ie. answer C) and achieving rapid growth rate (ie Ans D) etc. For this reason macroeconomics does not concern itself with competition between individuals and producers.',
                    created_at: '2011-08-11T06:43:13.000000Z',
                    updated_at: '2011-08-11T06:43:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 63356,
                    question_id: 16203,
                    text: 'Maintenance of full employment',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-11T06:43:13.000000Z',
                    updated_at: '2011-08-11T06:43:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 63357,
                    question_id: 16203,
                    text: 'Stabilization of prices',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-11T06:43:13.000000Z',
                    updated_at: '2011-08-11T06:43:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 63358,
                    question_id: 16203,
                    text: 'Achieving of prices',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-11T06:43:13.000000Z',
                    updated_at: '2011-08-11T06:43:13.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 16768,
            course_id: 1,
            topic_id: 0,
            qid: '015510EC00207',
            text: 'Labour is different from other factors of production because',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-08-12T13:37:08.000000Z',
            updated_at: '2011-08-12T13:37:08.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 65754,
                    question_id: 16768,
                    text: 'It can be counted',
                    value: 1,
                    solution: '',
                    created_at: '2011-08-12T13:37:08.000000Z',
                    updated_at: '2011-08-12T13:37:08.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 65755,
                    question_id: 16768,
                    text: 'Its contribution to production can change',
                    value: 1,
                    solution: '',
                    created_at: '2011-08-12T13:37:08.000000Z',
                    updated_at: '2011-08-12T13:37:08.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 65756,
                    question_id: 16768,
                    text: 'It can act on its own',
                    value: 1,
                    solution: '',
                    created_at: '2011-08-12T13:37:08.000000Z',
                    updated_at: '2011-08-12T13:37:08.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 65757,
                    question_id: 16768,
                    text: 'Its contribution to production does not change',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T13:37:08.000000Z',
                    updated_at: '2011-08-12T13:37:08.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 65758,
                    question_id: 16768,
                    text: 'Payment is made for its service.',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T13:37:08.000000Z',
                    updated_at: '2011-08-12T13:37:08.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 302,
            course_id: 1,
            topic_id: 7,
            qid: ': 01SS10EC30015',
            text: '<p>Which of the following description is true of a sole proprietor?</p>',
            instructions: '',
            resource: '',
            options: '',
            position: 15,
            created_at: '2018-05-30T22:48:50.000000Z',
            updated_at: '2018-05-30T22:48:50.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2","10617"]',
            editor_id: null,
            topic: {
                id: 7,
                course_id: 1,
                topicID: '01SS10EC30',
                name: 'BUSINESS ORGANIZATIONS ',
                author: 'content@ecoachsolutions.com',
                description: '',
                notes: '',
                category: '',
                created_at: '2011-08-03T00:00:00.000000Z',
                updated_at: '2017-03-15T15:45:53.000000Z',
                confirmed: 1,
                public: 1,
                N: 57,
                p: 57,
                editors: '["3","2","4668"]',
                editor_id: null,
            },
            answers: [
                {
                    id: 1235,
                    question_id: 302,
                    text: '<p>He enjoys limited liability</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-04T13:38:24.000000Z',
                    updated_at: '2011-08-04T13:38:24.000000Z',
                    answer_order: 1,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1236,
                    question_id: 302,
                    text: '<p>He can raise funds on the stock market</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-04T13:38:24.000000Z',
                    updated_at: '2011-08-04T13:38:24.000000Z',
                    answer_order: 2,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1237,
                    question_id: 302,
                    text: '<p>He enjoys flexibility in operation</p>',
                    value: 1,
                    solution:
                        '<p>A sole proprietor <strong><u data-redactor-tag="u">does not issue</u></strong> shares to raise capital since it ahs no mandate to do so. The sole proprietor can change its operation so easily as it does not need to consult anyone.</p>',
                    created_at: '2011-08-04T13:38:24.000000Z',
                    updated_at: '2011-08-04T13:38:24.000000Z',
                    answer_order: 3,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 1238,
                    question_id: 302,
                    text: '<p>Management and control are seperate</p>',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-04T13:38:24.000000Z',
                    updated_at: '2011-08-04T13:38:24.000000Z',
                    answer_order: 4,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 16920,
            course_id: 1,
            topic_id: 0,
            qid: '015510EC00281',
            text: "Some workers of a company are laid off because consumers' taste for its products has fallen. This is an example of",
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-08-12T17:43:56.000000Z',
            updated_at: '2011-08-12T17:43:56.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 66384,
                    question_id: 16920,
                    text: 'Structural unemployment',
                    value: 1,
                    solution: '',
                    created_at: '2011-08-12T17:43:56.000000Z',
                    updated_at: '2011-08-12T17:43:56.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 66385,
                    question_id: 16920,
                    text: 'Seasonal unemployment',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T17:43:56.000000Z',
                    updated_at: '2011-08-12T17:43:56.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 66386,
                    question_id: 16920,
                    text: 'Frictional unemployment',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T17:43:56.000000Z',
                    updated_at: '2011-08-12T17:43:56.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 66387,
                    question_id: 16920,
                    text: 'Cyclical unemployment',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-12T17:43:56.000000Z',
                    updated_at: '2011-08-12T17:43:56.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
        {
            id: 19058,
            course_id: 1,
            topic_id: 0,
            qid: '015510EC00784',
            text: 'Into which of the following markets is entry easiest?',
            instructions: '',
            resource: '',
            options: '',
            position: 0,
            created_at: '2011-08-18T17:44:51.000000Z',
            updated_at: '2011-08-18T17:44:51.000000Z',
            qtype: 'SINGLE',
            confirmed: 1,
            public: 1,
            flagged: 0,
            deleted: 0,
            editors: '["2"]',
            editor_id: null,
            topic: null,
            answers: [
                {
                    id: 75233,
                    question_id: 19058,
                    text: 'Imperfect competition',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-18T17:44:51.000000Z',
                    updated_at: '2011-08-18T17:44:51.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 75234,
                    question_id: 19058,
                    text: 'Monopolistic competition',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-18T17:44:51.000000Z',
                    updated_at: '2011-08-18T17:44:51.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 75235,
                    question_id: 19058,
                    text: 'Perfect competition',
                    value: 1,
                    solution:
                        'A firm can enter with ease so there is free mobility of resources.',
                    created_at: '2011-08-18T17:44:51.000000Z',
                    updated_at: '2011-08-18T17:44:51.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
                {
                    id: 75236,
                    question_id: 19058,
                    text: 'Pure monopoly',
                    value: 0,
                    solution: '',
                    created_at: '2011-08-18T17:44:51.000000Z',
                    updated_at: '2011-08-18T17:44:51.000000Z',
                    answer_order: 0,
                    responses: 0,
                    flagged: 1,
                    editors: '[]',
                    editor_id: null,
                },
            ],
        },
    ],
};

export default response;
